name: readeck_app
description: "ReadeckAPP - A mobile client for Readeck bookmark service."
publish_to: "none"
version: 0.0.2-beta

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - pubspec.yaml
