name: readeck_app
description: "ReadeckAPP - A mobile client for Readeck bookmark service."
publish_to: "none"
version: 0.1.0-beta

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  confetti: ^0.8.0
  go_router: ^14.6.2
  provider: ^6.1.5
  freezed_annotation: ^3.0.0
  freezed: ^3.0.6
  json_annotation: ^4.9.0

  sqflite: ^2.4.2
  path: ^1.9.1
  result_dart: ^2.1.0
  flutter_command: ^7.2.2
  sqflite_common: ^2.5.5
  intl: ^0.19.0
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - pubspec.yaml
