name: readeck_app
description: "ReadeckAPP - A mobile client for Readeck bookmark service."
publish_to: "none"
version: 0.4.1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  confetti: ^0.8.0
  go_router: ^14.6.2
  provider: ^6.1.5
  freezed_annotation: ^3.0.0
  freezed: ^3.0.6
  json_annotation: ^4.9.0

  sqflite: ^2.4.2
  path: ^1.9.1
  result_dart: ^2.1.0
  flutter_command: ^7.2.2
  sqflite_common: ^2.5.5
  intl: ^0.19.0
  logger: ^2.5.0
  sqlite3_flutter_libs: ^0.5.24
  flutter_html: ^3.0.0
  flutter_html_all: ^3.0.0
  photo_view: ^0.14.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  receive_sharing_intent: ^1.8.0
  html: ^0.15.4
  package_info_plus: ^8.0.0
  version: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.9.5
  sqflite_common_ffi: ^2.3.0
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - pubspec.yaml
