// Mocks generated by Mockito 5.4.6 from annotations
// in readeck_app/test/ui/bookmarks/view_models/add_bookmark_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:readeck_app/data/repository/ai_tag_recommendation/ai_tag_recommendation_repository.dart'
    as _i13;
import 'package:readeck_app/data/repository/bookmark/bookmark_repository.dart'
    as _i2;
import 'package:readeck_app/data/repository/label/label_repository.dart' as _i8;
import 'package:readeck_app/data/repository/settings/settings_repository.dart'
    as _i10;
import 'package:readeck_app/data/repository/web_content/web_content_repository.dart'
    as _i11;
import 'package:readeck_app/data/service/web_content_service.dart' as _i12;
import 'package:readeck_app/domain/models/bookmark/bookmark.dart' as _i7;
import 'package:readeck_app/domain/models/bookmark/label_info.dart' as _i9;
import 'package:readeck_app/domain/models/bookmark_display_model/bookmark_display_model.dart'
    as _i3;
import 'package:result_dart/result_dart.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BookmarkRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookmarkRepository extends _i1.Mock
    implements _i2.BookmarkRepository {
  @override
  List<_i3.BookmarkDisplayModel> get bookmarks => (super.noSuchMethod(
        Invocation.getter(#bookmarks),
        returnValue: <_i3.BookmarkDisplayModel>[],
        returnValueForMissingStub: <_i3.BookmarkDisplayModel>[],
      ) as List<_i3.BookmarkDisplayModel>);

  @override
  void addListener(_i2.BookmarkChangeListener? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i2.BookmarkChangeListener? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.BookmarkDisplayModel? getCachedBookmark(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedBookmark,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i3.BookmarkDisplayModel?);

  @override
  List<_i3.BookmarkDisplayModel?> getCachedBookmarks(List<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedBookmarks,
          [ids],
        ),
        returnValue: <_i3.BookmarkDisplayModel?>[],
        returnValueForMissingStub: <_i3.BookmarkDisplayModel?>[],
      ) as List<_i3.BookmarkDisplayModel?>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i5.ResultDart<List<_i3.BookmarkDisplayModel>, Exception>>
      loadBookmarksByIds(List<String>? ids) => (super.noSuchMethod(
            Invocation.method(
              #loadBookmarksByIds,
              [ids],
            ),
            returnValue: _i4.Future<
                _i5.ResultDart<List<_i3.BookmarkDisplayModel>,
                    Exception>>.value(_i6.dummyValue<
                _i5.ResultDart<List<_i3.BookmarkDisplayModel>, Exception>>(
              this,
              Invocation.method(
                #loadBookmarksByIds,
                [ids],
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                _i5.ResultDart<List<_i3.BookmarkDisplayModel>,
                    Exception>>.value(_i6.dummyValue<
                _i5.ResultDart<List<_i3.BookmarkDisplayModel>, Exception>>(
              this,
              Invocation.method(
                #loadBookmarksByIds,
                [ids],
              ),
            )),
          ) as _i4.Future<
              _i5.ResultDart<List<_i3.BookmarkDisplayModel>, Exception>>);

  @override
  _i4.Future<_i5.ResultDart<List<_i3.BookmarkDisplayModel>, Exception>>
      loadUnarchivedBookmarks({
    int? limit = 10,
    int? page = 1,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #loadUnarchivedBookmarks,
              [],
              {
                #limit: limit,
                #page: page,
              },
            ),
            returnValue: _i4.Future<
                _i5.ResultDart<List<_i3.BookmarkDisplayModel>,
                    Exception>>.value(_i6.dummyValue<
                _i5.ResultDart<List<_i3.BookmarkDisplayModel>, Exception>>(
              this,
              Invocation.method(
                #loadUnarchivedBookmarks,
                [],
                {
                  #limit: limit,
                  #page: page,
                },
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                _i5.ResultDart<List<_i3.BookmarkDisplayModel>,
                    Exception>>.value(_i6.dummyValue<
                _i5.ResultDart<List<_i3.BookmarkDisplayModel>, Exception>>(
              this,
              Invocation.method(
                #loadUnarchivedBookmarks,
                [],
                {
                  #limit: limit,
                  #page: page,
                },
              ),
            )),
          ) as _i4.Future<
              _i5.ResultDart<List<_i3.BookmarkDisplayModel>, Exception>>);

  @override
  _i4.Future<_i5.ResultDart<List<_i3.BookmarkDisplayModel>, Exception>>
      loadArchivedBookmarks({
    int? limit = 10,
    int? page = 1,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #loadArchivedBookmarks,
              [],
              {
                #limit: limit,
                #page: page,
              },
            ),
            returnValue: _i4.Future<
                _i5.ResultDart<List<_i3.BookmarkDisplayModel>,
                    Exception>>.value(_i6.dummyValue<
                _i5.ResultDart<List<_i3.BookmarkDisplayModel>, Exception>>(
              this,
              Invocation.method(
                #loadArchivedBookmarks,
                [],
                {
                  #limit: limit,
                  #page: page,
                },
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                _i5.ResultDart<List<_i3.BookmarkDisplayModel>,
                    Exception>>.value(_i6.dummyValue<
                _i5.ResultDart<List<_i3.BookmarkDisplayModel>, Exception>>(
              this,
              Invocation.method(
                #loadArchivedBookmarks,
                [],
                {
                  #limit: limit,
                  #page: page,
                },
              ),
            )),
          ) as _i4.Future<
              _i5.ResultDart<List<_i3.BookmarkDisplayModel>, Exception>>);

  @override
  _i4.Future<_i5.ResultDart<List<_i3.BookmarkDisplayModel>, Exception>>
      loadMarkedBookmarks({
    int? limit = 10,
    int? page = 1,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #loadMarkedBookmarks,
              [],
              {
                #limit: limit,
                #page: page,
              },
            ),
            returnValue: _i4.Future<
                _i5.ResultDart<List<_i3.BookmarkDisplayModel>,
                    Exception>>.value(_i6.dummyValue<
                _i5.ResultDart<List<_i3.BookmarkDisplayModel>, Exception>>(
              this,
              Invocation.method(
                #loadMarkedBookmarks,
                [],
                {
                  #limit: limit,
                  #page: page,
                },
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                _i5.ResultDart<List<_i3.BookmarkDisplayModel>,
                    Exception>>.value(_i6.dummyValue<
                _i5.ResultDart<List<_i3.BookmarkDisplayModel>, Exception>>(
              this,
              Invocation.method(
                #loadMarkedBookmarks,
                [],
                {
                  #limit: limit,
                  #page: page,
                },
              ),
            )),
          ) as _i4.Future<
              _i5.ResultDart<List<_i3.BookmarkDisplayModel>, Exception>>);

  @override
  _i4.Future<_i5.ResultDart<List<_i3.BookmarkDisplayModel>, Exception>>
      loadReadingBookmarks({
    int? limit = 10,
    int? page = 1,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #loadReadingBookmarks,
              [],
              {
                #limit: limit,
                #page: page,
              },
            ),
            returnValue: _i4.Future<
                _i5.ResultDart<List<_i3.BookmarkDisplayModel>,
                    Exception>>.value(_i6.dummyValue<
                _i5.ResultDart<List<_i3.BookmarkDisplayModel>, Exception>>(
              this,
              Invocation.method(
                #loadReadingBookmarks,
                [],
                {
                  #limit: limit,
                  #page: page,
                },
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                _i5.ResultDart<List<_i3.BookmarkDisplayModel>,
                    Exception>>.value(_i6.dummyValue<
                _i5.ResultDart<List<_i3.BookmarkDisplayModel>, Exception>>(
              this,
              Invocation.method(
                #loadReadingBookmarks,
                [],
                {
                  #limit: limit,
                  #page: page,
                },
              ),
            )),
          ) as _i4.Future<
              _i5.ResultDart<List<_i3.BookmarkDisplayModel>, Exception>>);

  @override
  _i4.Future<_i5.ResultDart<List<_i3.BookmarkDisplayModel>, Exception>>
      loadRandomUnarchivedBookmarks(int? randomCount) => (super.noSuchMethod(
            Invocation.method(
              #loadRandomUnarchivedBookmarks,
              [randomCount],
            ),
            returnValue: _i4.Future<
                _i5.ResultDart<List<_i3.BookmarkDisplayModel>,
                    Exception>>.value(_i6.dummyValue<
                _i5.ResultDart<List<_i3.BookmarkDisplayModel>, Exception>>(
              this,
              Invocation.method(
                #loadRandomUnarchivedBookmarks,
                [randomCount],
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                _i5.ResultDart<List<_i3.BookmarkDisplayModel>,
                    Exception>>.value(_i6.dummyValue<
                _i5.ResultDart<List<_i3.BookmarkDisplayModel>, Exception>>(
              this,
              Invocation.method(
                #loadRandomUnarchivedBookmarks,
                [randomCount],
              ),
            )),
          ) as _i4.Future<
              _i5.ResultDart<List<_i3.BookmarkDisplayModel>, Exception>>);

  @override
  _i4.Future<_i5.ResultDart<void, Exception>> toggleMarked(
          _i7.Bookmark? bookmark) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleMarked,
          [bookmark],
        ),
        returnValue: _i4.Future<_i5.ResultDart<void, Exception>>.value(
            _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #toggleMarked,
            [bookmark],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.ResultDart<void, Exception>>.value(
                _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #toggleMarked,
            [bookmark],
          ),
        )),
      ) as _i4.Future<_i5.ResultDart<void, Exception>>);

  @override
  _i4.Future<_i5.ResultDart<void, Exception>> toggleArchived(
          _i7.Bookmark? bookmark) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleArchived,
          [bookmark],
        ),
        returnValue: _i4.Future<_i5.ResultDart<void, Exception>>.value(
            _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #toggleArchived,
            [bookmark],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.ResultDart<void, Exception>>.value(
                _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #toggleArchived,
            [bookmark],
          ),
        )),
      ) as _i4.Future<_i5.ResultDart<void, Exception>>);

  @override
  _i4.Future<_i5.ResultDart<void, Exception>> updateLabels(
    _i7.Bookmark? bookmark,
    List<String>? labels,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLabels,
          [
            bookmark,
            labels,
          ],
        ),
        returnValue: _i4.Future<_i5.ResultDart<void, Exception>>.value(
            _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #updateLabels,
            [
              bookmark,
              labels,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.ResultDart<void, Exception>>.value(
                _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #updateLabels,
            [
              bookmark,
              labels,
            ],
          ),
        )),
      ) as _i4.Future<_i5.ResultDart<void, Exception>>);

  @override
  _i4.Future<_i5.ResultDart<void, Exception>> updateReadProgress(
    _i7.Bookmark? bookmark,
    int? readProgress,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReadProgress,
          [
            bookmark,
            readProgress,
          ],
        ),
        returnValue: _i4.Future<_i5.ResultDart<void, Exception>>.value(
            _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #updateReadProgress,
            [
              bookmark,
              readProgress,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.ResultDart<void, Exception>>.value(
                _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #updateReadProgress,
            [
              bookmark,
              readProgress,
            ],
          ),
        )),
      ) as _i4.Future<_i5.ResultDart<void, Exception>>);

  @override
  _i4.Future<_i5.ResultDart<void, Exception>> createBookmark({
    required String? url,
    String? title,
    List<String>? labels,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBookmark,
          [],
          {
            #url: url,
            #title: title,
            #labels: labels,
          },
        ),
        returnValue: _i4.Future<_i5.ResultDart<void, Exception>>.value(
            _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #createBookmark,
            [],
            {
              #url: url,
              #title: title,
              #labels: labels,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.ResultDart<void, Exception>>.value(
                _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #createBookmark,
            [],
            {
              #url: url,
              #title: title,
              #labels: labels,
            },
          ),
        )),
      ) as _i4.Future<_i5.ResultDart<void, Exception>>);

  @override
  _i4.Future<_i5.ResultDart<void, Exception>> deleteBookmark(
          String? bookmarkId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBookmark,
          [bookmarkId],
        ),
        returnValue: _i4.Future<_i5.ResultDart<void, Exception>>.value(
            _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #deleteBookmark,
            [bookmarkId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.ResultDart<void, Exception>>.value(
                _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #deleteBookmark,
            [bookmarkId],
          ),
        )),
      ) as _i4.Future<_i5.ResultDart<void, Exception>>);
}

/// A class which mocks [LabelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLabelRepository extends _i1.Mock implements _i8.LabelRepository {
  @override
  List<_i9.LabelInfo> get labels => (super.noSuchMethod(
        Invocation.getter(#labels),
        returnValue: <_i9.LabelInfo>[],
        returnValueForMissingStub: <_i9.LabelInfo>[],
      ) as List<_i9.LabelInfo>);

  @override
  List<String> get labelNames => (super.noSuchMethod(
        Invocation.getter(#labelNames),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  void addListener(_i8.LabelChangeListener? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.LabelChangeListener? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void insertOrUpdateLabel(_i9.LabelInfo? label) => super.noSuchMethod(
        Invocation.method(
          #insertOrUpdateLabel,
          [label],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.LabelInfo? getCachedLabel(String? name) => (super.noSuchMethod(
        Invocation.method(
          #getCachedLabel,
          [name],
        ),
        returnValueForMissingStub: null,
      ) as _i9.LabelInfo?);

  @override
  List<_i9.LabelInfo> getCachedLabels(List<String>? names) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedLabels,
          [names],
        ),
        returnValue: <_i9.LabelInfo>[],
        returnValueForMissingStub: <_i9.LabelInfo>[],
      ) as List<_i9.LabelInfo>);

  @override
  _i4.Future<_i5.ResultDart<List<_i9.LabelInfo>, Exception>> loadLabels() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadLabels,
          [],
        ),
        returnValue:
            _i4.Future<_i5.ResultDart<List<_i9.LabelInfo>, Exception>>.value(
                _i6.dummyValue<_i5.ResultDart<List<_i9.LabelInfo>, Exception>>(
          this,
          Invocation.method(
            #loadLabels,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.ResultDart<List<_i9.LabelInfo>, Exception>>.value(
                _i6.dummyValue<_i5.ResultDart<List<_i9.LabelInfo>, Exception>>(
          this,
          Invocation.method(
            #loadLabels,
            [],
          ),
        )),
      ) as _i4.Future<_i5.ResultDart<List<_i9.LabelInfo>, Exception>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i10.SettingsRepository {
  @override
  _i4.Stream<void> get settingsChanged => (super.noSuchMethod(
        Invocation.getter(#settingsChanged),
        returnValue: _i4.Stream<void>.empty(),
        returnValueForMissingStub: _i4.Stream<void>.empty(),
      ) as _i4.Stream<void>);

  @override
  _i4.Future<_i5.ResultDart<void, Exception>> loadSettings() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadSettings,
          [],
        ),
        returnValue: _i4.Future<_i5.ResultDart<void, Exception>>.value(
            _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #loadSettings,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.ResultDart<void, Exception>>.value(
                _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #loadSettings,
            [],
          ),
        )),
      ) as _i4.Future<_i5.ResultDart<void, Exception>>);

  @override
  bool isApiConfigured() => (super.noSuchMethod(
        Invocation.method(
          #isApiConfigured,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Future<_i5.ResultDart<void, Exception>> saveApiConfig(
    String? host,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveApiConfig,
          [
            host,
            token,
          ],
        ),
        returnValue: _i4.Future<_i5.ResultDart<void, Exception>>.value(
            _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveApiConfig,
            [
              host,
              token,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.ResultDart<void, Exception>>.value(
                _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveApiConfig,
            [
              host,
              token,
            ],
          ),
        )),
      ) as _i4.Future<_i5.ResultDart<void, Exception>>);

  @override
  (String, String) getApiConfig() => (super.noSuchMethod(
        Invocation.method(
          #getApiConfig,
          [],
        ),
        returnValue: (
          _i6.dummyValue<String>(
            this,
            Invocation.method(
              #getApiConfig,
              [],
            ),
          ),
          _i6.dummyValue<String>(
            this,
            Invocation.method(
              #getApiConfig,
              [],
            ),
          )
        ),
        returnValueForMissingStub: (
          _i6.dummyValue<String>(
            this,
            Invocation.method(
              #getApiConfig,
              [],
            ),
          ),
          _i6.dummyValue<String>(
            this,
            Invocation.method(
              #getApiConfig,
              [],
            ),
          )
        ),
      ) as (String, String));

  @override
  int getThemeMode() => (super.noSuchMethod(
        Invocation.method(
          #getThemeMode,
          [],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i4.Future<_i5.ResultDart<void, Exception>> saveThemeMode(int? themeMode) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveThemeMode,
          [themeMode],
        ),
        returnValue: _i4.Future<_i5.ResultDart<void, Exception>>.value(
            _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveThemeMode,
            [themeMode],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.ResultDart<void, Exception>>.value(
                _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveThemeMode,
            [themeMode],
          ),
        )),
      ) as _i4.Future<_i5.ResultDart<void, Exception>>);

  @override
  _i4.Future<_i5.ResultDart<void, Exception>> saveOpenRouterApiKey(
          String? apiKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveOpenRouterApiKey,
          [apiKey],
        ),
        returnValue: _i4.Future<_i5.ResultDart<void, Exception>>.value(
            _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveOpenRouterApiKey,
            [apiKey],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.ResultDart<void, Exception>>.value(
                _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveOpenRouterApiKey,
            [apiKey],
          ),
        )),
      ) as _i4.Future<_i5.ResultDart<void, Exception>>);

  @override
  String getOpenRouterApiKey() => (super.noSuchMethod(
        Invocation.method(
          #getOpenRouterApiKey,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getOpenRouterApiKey,
            [],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getOpenRouterApiKey,
            [],
          ),
        ),
      ) as String);

  @override
  _i4.Future<_i5.ResultDart<void, Exception>> saveTranslationProvider(
          String? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTranslationProvider,
          [provider],
        ),
        returnValue: _i4.Future<_i5.ResultDart<void, Exception>>.value(
            _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveTranslationProvider,
            [provider],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.ResultDart<void, Exception>>.value(
                _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveTranslationProvider,
            [provider],
          ),
        )),
      ) as _i4.Future<_i5.ResultDart<void, Exception>>);

  @override
  String getTranslationProvider() => (super.noSuchMethod(
        Invocation.method(
          #getTranslationProvider,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getTranslationProvider,
            [],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getTranslationProvider,
            [],
          ),
        ),
      ) as String);

  @override
  _i4.Future<_i5.ResultDart<void, Exception>> saveTranslationTargetLanguage(
          String? language) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTranslationTargetLanguage,
          [language],
        ),
        returnValue: _i4.Future<_i5.ResultDart<void, Exception>>.value(
            _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveTranslationTargetLanguage,
            [language],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.ResultDart<void, Exception>>.value(
                _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveTranslationTargetLanguage,
            [language],
          ),
        )),
      ) as _i4.Future<_i5.ResultDart<void, Exception>>);

  @override
  String getTranslationTargetLanguage() => (super.noSuchMethod(
        Invocation.method(
          #getTranslationTargetLanguage,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getTranslationTargetLanguage,
            [],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getTranslationTargetLanguage,
            [],
          ),
        ),
      ) as String);

  @override
  _i4.Future<_i5.ResultDart<void, Exception>> saveTranslationCacheEnabled(
          bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTranslationCacheEnabled,
          [enabled],
        ),
        returnValue: _i4.Future<_i5.ResultDart<void, Exception>>.value(
            _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveTranslationCacheEnabled,
            [enabled],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.ResultDart<void, Exception>>.value(
                _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveTranslationCacheEnabled,
            [enabled],
          ),
        )),
      ) as _i4.Future<_i5.ResultDart<void, Exception>>);

  @override
  bool getTranslationCacheEnabled() => (super.noSuchMethod(
        Invocation.method(
          #getTranslationCacheEnabled,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Future<_i5.ResultDart<void, Exception>> saveSelectedOpenRouterModel(
          String? modelId) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSelectedOpenRouterModel,
          [modelId],
        ),
        returnValue: _i4.Future<_i5.ResultDart<void, Exception>>.value(
            _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveSelectedOpenRouterModel,
            [modelId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.ResultDart<void, Exception>>.value(
                _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveSelectedOpenRouterModel,
            [modelId],
          ),
        )),
      ) as _i4.Future<_i5.ResultDart<void, Exception>>);

  @override
  String getSelectedOpenRouterModel() => (super.noSuchMethod(
        Invocation.method(
          #getSelectedOpenRouterModel,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getSelectedOpenRouterModel,
            [],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getSelectedOpenRouterModel,
            [],
          ),
        ),
      ) as String);

  @override
  _i4.Future<_i5.ResultDart<void, Exception>> saveAiTagTargetLanguage(
          String? language) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAiTagTargetLanguage,
          [language],
        ),
        returnValue: _i4.Future<_i5.ResultDart<void, Exception>>.value(
            _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveAiTagTargetLanguage,
            [language],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.ResultDart<void, Exception>>.value(
                _i6.dummyValue<_i5.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveAiTagTargetLanguage,
            [language],
          ),
        )),
      ) as _i4.Future<_i5.ResultDart<void, Exception>>);

  @override
  String getAiTagTargetLanguage() => (super.noSuchMethod(
        Invocation.method(
          #getAiTagTargetLanguage,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getAiTagTargetLanguage,
            [],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getAiTagTargetLanguage,
            [],
          ),
        ),
      ) as String);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [WebContentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebContentRepository extends _i1.Mock
    implements _i11.WebContentRepository {
  @override
  _i4.Future<_i5.ResultDart<_i12.WebContent, Exception>> fetchWebContent(
    String? url, {
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchWebContent,
          [url],
          {#timeout: timeout},
        ),
        returnValue:
            _i4.Future<_i5.ResultDart<_i12.WebContent, Exception>>.value(
                _i6.dummyValue<_i5.ResultDart<_i12.WebContent, Exception>>(
          this,
          Invocation.method(
            #fetchWebContent,
            [url],
            {#timeout: timeout},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.ResultDart<_i12.WebContent, Exception>>.value(
                _i6.dummyValue<_i5.ResultDart<_i12.WebContent, Exception>>(
          this,
          Invocation.method(
            #fetchWebContent,
            [url],
            {#timeout: timeout},
          ),
        )),
      ) as _i4.Future<_i5.ResultDart<_i12.WebContent, Exception>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AiTagRecommendationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiTagRecommendationRepository extends _i1.Mock
    implements _i13.AiTagRecommendationRepository {
  @override
  bool get isAvailable => (super.noSuchMethod(
        Invocation.getter(#isAvailable),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Future<_i5.ResultDart<List<String>, Exception>>
      generateTagRecommendations(
    _i12.WebContent? webContent,
    List<String>? existingTags, {
    int? maxTags = 5,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #generateTagRecommendations,
              [
                webContent,
                existingTags,
              ],
              {#maxTags: maxTags},
            ),
            returnValue:
                _i4.Future<_i5.ResultDart<List<String>, Exception>>.value(
                    _i6.dummyValue<_i5.ResultDart<List<String>, Exception>>(
              this,
              Invocation.method(
                #generateTagRecommendations,
                [
                  webContent,
                  existingTags,
                ],
                {#maxTags: maxTags},
              ),
            )),
            returnValueForMissingStub:
                _i4.Future<_i5.ResultDart<List<String>, Exception>>.value(
                    _i6.dummyValue<_i5.ResultDart<List<String>, Exception>>(
              this,
              Invocation.method(
                #generateTagRecommendations,
                [
                  webContent,
                  existingTags,
                ],
                {#maxTags: maxTags},
              ),
            )),
          ) as _i4.Future<_i5.ResultDart<List<String>, Exception>>);
}
