// Mocks generated by Mockito 5.4.6 from annotations
// in readeck_app/test/ui/settings/view_models/ai_settings_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:readeck_app/data/repository/openrouter/openrouter_repository.dart'
    as _i6;
import 'package:readeck_app/data/repository/settings/settings_repository.dart'
    as _i2;
import 'package:readeck_app/domain/models/openrouter_model/openrouter_model.dart'
    as _i7;
import 'package:result_dart/result_dart.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i2.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<void> get settingsChanged => (super.noSuchMethod(
        Invocation.getter(#settingsChanged),
        returnValue: _i3.Stream<void>.empty(),
      ) as _i3.Stream<void>);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> loadSettings() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadSettings,
          [],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #loadSettings,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  bool isApiConfigured() => (super.noSuchMethod(
        Invocation.method(
          #isApiConfigured,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> saveApiConfig(
    String? host,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveApiConfig,
          [
            host,
            token,
          ],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveApiConfig,
            [
              host,
              token,
            ],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  (String, String) getApiConfig() => (super.noSuchMethod(
        Invocation.method(
          #getApiConfig,
          [],
        ),
        returnValue: (
          _i5.dummyValue<String>(
            this,
            Invocation.method(
              #getApiConfig,
              [],
            ),
          ),
          _i5.dummyValue<String>(
            this,
            Invocation.method(
              #getApiConfig,
              [],
            ),
          )
        ),
      ) as (String, String));

  @override
  int getThemeMode() => (super.noSuchMethod(
        Invocation.method(
          #getThemeMode,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> saveThemeMode(int? themeMode) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveThemeMode,
          [themeMode],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveThemeMode,
            [themeMode],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> saveOpenRouterApiKey(
          String? apiKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveOpenRouterApiKey,
          [apiKey],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveOpenRouterApiKey,
            [apiKey],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  String getOpenRouterApiKey() => (super.noSuchMethod(
        Invocation.method(
          #getOpenRouterApiKey,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getOpenRouterApiKey,
            [],
          ),
        ),
      ) as String);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> saveTranslationProvider(
          String? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTranslationProvider,
          [provider],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveTranslationProvider,
            [provider],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  String getTranslationProvider() => (super.noSuchMethod(
        Invocation.method(
          #getTranslationProvider,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getTranslationProvider,
            [],
          ),
        ),
      ) as String);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> saveTranslationTargetLanguage(
          String? language) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTranslationTargetLanguage,
          [language],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveTranslationTargetLanguage,
            [language],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  String getTranslationTargetLanguage() => (super.noSuchMethod(
        Invocation.method(
          #getTranslationTargetLanguage,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getTranslationTargetLanguage,
            [],
          ),
        ),
      ) as String);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> saveTranslationCacheEnabled(
          bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTranslationCacheEnabled,
          [enabled],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveTranslationCacheEnabled,
            [enabled],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  bool getTranslationCacheEnabled() => (super.noSuchMethod(
        Invocation.method(
          #getTranslationCacheEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> saveSelectedOpenRouterModel(
    String? modelId, [
    String? modelName,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSelectedOpenRouterModel,
          [
            modelId,
            modelName,
          ],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveSelectedOpenRouterModel,
            [
              modelId,
              modelName,
            ],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  String getSelectedOpenRouterModel() => (super.noSuchMethod(
        Invocation.method(
          #getSelectedOpenRouterModel,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getSelectedOpenRouterModel,
            [],
          ),
        ),
      ) as String);

  @override
  String getSelectedOpenRouterModelName() => (super.noSuchMethod(
        Invocation.method(
          #getSelectedOpenRouterModelName,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getSelectedOpenRouterModelName,
            [],
          ),
        ),
      ) as String);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> saveAiTagTargetLanguage(
          String? language) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAiTagTargetLanguage,
          [language],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveAiTagTargetLanguage,
            [language],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  String getAiTagTargetLanguage() => (super.noSuchMethod(
        Invocation.method(
          #getAiTagTargetLanguage,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getAiTagTargetLanguage,
            [],
          ),
        ),
      ) as String);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> saveTranslationModel(
    String? modelId, [
    String? modelName,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTranslationModel,
          [
            modelId,
            modelName,
          ],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveTranslationModel,
            [
              modelId,
              modelName,
            ],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  String getTranslationModel() => (super.noSuchMethod(
        Invocation.method(
          #getTranslationModel,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getTranslationModel,
            [],
          ),
        ),
      ) as String);

  @override
  String getTranslationModelName() => (super.noSuchMethod(
        Invocation.method(
          #getTranslationModelName,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getTranslationModelName,
            [],
          ),
        ),
      ) as String);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> saveAiTagModel(
    String? modelId, [
    String? modelName,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAiTagModel,
          [
            modelId,
            modelName,
          ],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveAiTagModel,
            [
              modelId,
              modelName,
            ],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  String getAiTagModel() => (super.noSuchMethod(
        Invocation.method(
          #getAiTagModel,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getAiTagModel,
            [],
          ),
        ),
      ) as String);

  @override
  String getAiTagModelName() => (super.noSuchMethod(
        Invocation.method(
          #getAiTagModelName,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getAiTagModelName,
            [],
          ),
        ),
      ) as String);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [OpenRouterRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenRouterRepository extends _i1.Mock
    implements _i6.OpenRouterRepository {
  MockOpenRouterRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ResultDart<List<_i7.OpenRouterModel>, Exception>> getModels(
          {String? category}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getModels,
          [],
          {#category: category},
        ),
        returnValue: _i3
            .Future<_i4.ResultDart<List<_i7.OpenRouterModel>, Exception>>.value(
            _i5.dummyValue<
                _i4.ResultDart<List<_i7.OpenRouterModel>, Exception>>(
          this,
          Invocation.method(
            #getModels,
            [],
            {#category: category},
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<List<_i7.OpenRouterModel>, Exception>>);
}
