// Mocks generated by Mockito 5.4.6 from annotations
// in readeck_app/test/data/repository/settings_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:readeck_app/data/service/readeck_api_client.dart' as _i6;
import 'package:readeck_app/data/service/shared_preference_service.dart' as _i2;
import 'package:readeck_app/domain/models/bookmark/bookmark.dart' as _i7;
import 'package:readeck_app/domain/models/bookmark/label_info.dart' as _i8;
import 'package:result_dart/result_dart.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SharedPreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferencesService extends _i1.Mock
    implements _i2.SharedPreferencesService {
  MockSharedPreferencesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> setThemeMode(int? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [value],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #setThemeMode,
            [value],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<int, Exception>> getThemeMode() =>
      (super.noSuchMethod(
        Invocation.method(
          #getThemeMode,
          [],
        ),
        returnValue: _i3.Future<_i4.ResultDart<int, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<int, Exception>>(
          this,
          Invocation.method(
            #getThemeMode,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<int, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> setReadeckApiHost(
          String? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setReadeckApiHost,
          [value],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #setReadeckApiHost,
            [value],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<String, Exception>> getReadeckApiHost() =>
      (super.noSuchMethod(
        Invocation.method(
          #getReadeckApiHost,
          [],
        ),
        returnValue: _i3.Future<_i4.ResultDart<String, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<String, Exception>>(
          this,
          Invocation.method(
            #getReadeckApiHost,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<String, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> setReadeckApiToken(
          String? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setReadeckApiToken,
          [value],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #setReadeckApiToken,
            [value],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<String, Exception>> getReadeckApiToken() =>
      (super.noSuchMethod(
        Invocation.method(
          #getReadeckApiToken,
          [],
        ),
        returnValue: _i3.Future<_i4.ResultDart<String, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<String, Exception>>(
          this,
          Invocation.method(
            #getReadeckApiToken,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<String, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> setOpenRouterApiKey(
          String? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOpenRouterApiKey,
          [value],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #setOpenRouterApiKey,
            [value],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<String, Exception>> getOpenRouterApiKey() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOpenRouterApiKey,
          [],
        ),
        returnValue: _i3.Future<_i4.ResultDart<String, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<String, Exception>>(
          this,
          Invocation.method(
            #getOpenRouterApiKey,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<String, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> setSelectedOpenRouterModel(
          String? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSelectedOpenRouterModel,
          [value],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #setSelectedOpenRouterModel,
            [value],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<String, Exception>> getSelectedOpenRouterModel() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSelectedOpenRouterModel,
          [],
        ),
        returnValue: _i3.Future<_i4.ResultDart<String, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<String, Exception>>(
          this,
          Invocation.method(
            #getSelectedOpenRouterModel,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<String, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> setTranslationProvider(
          String? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTranslationProvider,
          [value],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #setTranslationProvider,
            [value],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<String, Exception>> getTranslationProvider() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTranslationProvider,
          [],
        ),
        returnValue: _i3.Future<_i4.ResultDart<String, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<String, Exception>>(
          this,
          Invocation.method(
            #getTranslationProvider,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<String, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> setTranslationTargetLanguage(
          String? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTranslationTargetLanguage,
          [value],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #setTranslationTargetLanguage,
            [value],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<String, Exception>>
      getTranslationTargetLanguage() => (super.noSuchMethod(
            Invocation.method(
              #getTranslationTargetLanguage,
              [],
            ),
            returnValue: _i3.Future<_i4.ResultDart<String, Exception>>.value(
                _i5.dummyValue<_i4.ResultDart<String, Exception>>(
              this,
              Invocation.method(
                #getTranslationTargetLanguage,
                [],
              ),
            )),
          ) as _i3.Future<_i4.ResultDart<String, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> setTranslationCacheEnabled(
          bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTranslationCacheEnabled,
          [value],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #setTranslationCacheEnabled,
            [value],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<bool, Exception>> getTranslationCacheEnabled() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTranslationCacheEnabled,
          [],
        ),
        returnValue: _i3.Future<_i4.ResultDart<bool, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<bool, Exception>>(
          this,
          Invocation.method(
            #getTranslationCacheEnabled,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<bool, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> setAiTagTargetLanguage(
          String? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAiTagTargetLanguage,
          [value],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #setAiTagTargetLanguage,
            [value],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<String, Exception>> getAiTagTargetLanguage() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAiTagTargetLanguage,
          [],
        ),
        returnValue: _i3.Future<_i4.ResultDart<String, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<String, Exception>>(
          this,
          Invocation.method(
            #getAiTagTargetLanguage,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<String, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> setTranslationModel(
          String? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTranslationModel,
          [value],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #setTranslationModel,
            [value],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<String, Exception>> getTranslationModel() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTranslationModel,
          [],
        ),
        returnValue: _i3.Future<_i4.ResultDart<String, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<String, Exception>>(
          this,
          Invocation.method(
            #getTranslationModel,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<String, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> setAiTagModel(String? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAiTagModel,
          [value],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #setAiTagModel,
            [value],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<String, Exception>> getAiTagModel() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAiTagModel,
          [],
        ),
        returnValue: _i3.Future<_i4.ResultDart<String, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<String, Exception>>(
          this,
          Invocation.method(
            #getAiTagModel,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<String, Exception>>);
}

/// A class which mocks [ReadeckApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockReadeckApiClient extends _i1.Mock implements _i6.ReadeckApiClient {
  MockReadeckApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void updateConfig(
    String? host,
    String? token,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateConfig,
          [
            host,
            token,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<_i4.ResultDart<List<_i7.Bookmark>, Exception>> getBookmarks({
    String? search,
    String? title,
    String? author,
    String? site,
    String? type,
    List<String>? labels,
    bool? isLoaded,
    bool? hasErrors,
    bool? hasLabels,
    bool? isMarked,
    bool? isArchived,
    String? rangeStart,
    String? rangeEnd,
    String? readStatus,
    String? updatedSince,
    List<String>? ids,
    String? collection,
    String? sort,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookmarks,
          [],
          {
            #search: search,
            #title: title,
            #author: author,
            #site: site,
            #type: type,
            #labels: labels,
            #isLoaded: isLoaded,
            #hasErrors: hasErrors,
            #hasLabels: hasLabels,
            #isMarked: isMarked,
            #isArchived: isArchived,
            #rangeStart: rangeStart,
            #rangeEnd: rangeEnd,
            #readStatus: readStatus,
            #updatedSince: updatedSince,
            #ids: ids,
            #collection: collection,
            #sort: sort,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i3.Future<_i4.ResultDart<List<_i7.Bookmark>, Exception>>.value(
                _i5.dummyValue<_i4.ResultDart<List<_i7.Bookmark>, Exception>>(
          this,
          Invocation.method(
            #getBookmarks,
            [],
            {
              #search: search,
              #title: title,
              #author: author,
              #site: site,
              #type: type,
              #labels: labels,
              #isLoaded: isLoaded,
              #hasErrors: hasErrors,
              #hasLabels: hasLabels,
              #isMarked: isMarked,
              #isArchived: isArchived,
              #rangeStart: rangeStart,
              #rangeEnd: rangeEnd,
              #readStatus: readStatus,
              #updatedSince: updatedSince,
              #ids: ids,
              #collection: collection,
              #sort: sort,
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<List<_i7.Bookmark>, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<Map<String, dynamic>, Exception>> updateBookmark(
    String? bookmarkId, {
    String? title,
    bool? isMarked,
    bool? isArchived,
    bool? isDeleted,
    int? readProgress,
    String? readAnchor,
    List<String>? labels,
    List<String>? addLabels,
    List<String>? removeLabels,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBookmark,
          [bookmarkId],
          {
            #title: title,
            #isMarked: isMarked,
            #isArchived: isArchived,
            #isDeleted: isDeleted,
            #readProgress: readProgress,
            #readAnchor: readAnchor,
            #labels: labels,
            #addLabels: addLabels,
            #removeLabels: removeLabels,
          },
        ),
        returnValue:
            _i3.Future<_i4.ResultDart<Map<String, dynamic>, Exception>>.value(
                _i5.dummyValue<_i4.ResultDart<Map<String, dynamic>, Exception>>(
          this,
          Invocation.method(
            #updateBookmark,
            [bookmarkId],
            {
              #title: title,
              #isMarked: isMarked,
              #isArchived: isArchived,
              #isDeleted: isDeleted,
              #readProgress: readProgress,
              #readAnchor: readAnchor,
              #labels: labels,
              #addLabels: addLabels,
              #removeLabels: removeLabels,
            },
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<Map<String, dynamic>, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<List<_i8.LabelInfo>, Exception>> getLabels() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLabels,
          [],
        ),
        returnValue:
            _i3.Future<_i4.ResultDart<List<_i8.LabelInfo>, Exception>>.value(
                _i5.dummyValue<_i4.ResultDart<List<_i8.LabelInfo>, Exception>>(
          this,
          Invocation.method(
            #getLabels,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<List<_i8.LabelInfo>, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<String, Exception>> getBookmarkArticle(
          String? bookmarkId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookmarkArticle,
          [bookmarkId],
        ),
        returnValue: _i3.Future<_i4.ResultDart<String, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<String, Exception>>(
          this,
          Invocation.method(
            #getBookmarkArticle,
            [bookmarkId],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<String, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> createBookmark({
    required String? url,
    String? title,
    List<String>? labels,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBookmark,
          [],
          {
            #url: url,
            #title: title,
            #labels: labels,
          },
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #createBookmark,
            [],
            {
              #url: url,
              #title: title,
              #labels: labels,
            },
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> deleteBookmark(
          String? bookmarkId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBookmark,
          [bookmarkId],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #deleteBookmark,
            [bookmarkId],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);
}
