// Mocks generated by Mockito 5.4.6 from annotations
// in readeck_app/test/ui/settings/widgets/model_selection_screen_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i6;

import 'package:flutter_command/flutter_command.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:readeck_app/domain/models/openrouter_model/openrouter_model.dart'
    as _i4;
import 'package:readeck_app/ui/settings/view_models/model_selection_viewmodel.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCommand_0<TParam, TResult> extends _i1.SmartFake
    implements _i2.Command<TParam, TResult> {
  _FakeCommand_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ModelSelectionViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockModelSelectionViewModel extends _i1.Mock
    implements _i3.ModelSelectionViewModel {
  @override
  _i2.Command<void, List<_i4.OpenRouterModel>> get loadModels =>
      (super.noSuchMethod(
        Invocation.getter(#loadModels),
        returnValue: _FakeCommand_0<void, List<_i4.OpenRouterModel>>(
          this,
          Invocation.getter(#loadModels),
        ),
        returnValueForMissingStub:
            _FakeCommand_0<void, List<_i4.OpenRouterModel>>(
          this,
          Invocation.getter(#loadModels),
        ),
      ) as _i2.Command<void, List<_i4.OpenRouterModel>>);

  @override
  _i2.Command<void, void> get loadSelectedModel => (super.noSuchMethod(
        Invocation.getter(#loadSelectedModel),
        returnValue: _FakeCommand_0<void, void>(
          this,
          Invocation.getter(#loadSelectedModel),
        ),
        returnValueForMissingStub: _FakeCommand_0<void, void>(
          this,
          Invocation.getter(#loadSelectedModel),
        ),
      ) as _i2.Command<void, void>);

  @override
  List<_i4.OpenRouterModel> get availableModels => (super.noSuchMethod(
        Invocation.getter(#availableModels),
        returnValue: <_i4.OpenRouterModel>[],
        returnValueForMissingStub: <_i4.OpenRouterModel>[],
      ) as List<_i4.OpenRouterModel>);

  @override
  bool get isUsingGlobalModel => (super.noSuchMethod(
        Invocation.getter(#isUsingGlobalModel),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get globalModelName => (super.noSuchMethod(
        Invocation.getter(#globalModelName),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#globalModelName),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#globalModelName),
        ),
      ) as String);

  @override
  String get globalModelId => (super.noSuchMethod(
        Invocation.getter(#globalModelId),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#globalModelId),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#globalModelId),
        ),
      ) as String);

  @override
  set loadModels(_i2.Command<void, List<_i4.OpenRouterModel>>? _loadModels) =>
      super.noSuchMethod(
        Invocation.setter(
          #loadModels,
          _loadModels,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set loadSelectedModel(_i2.Command<void, void>? _loadSelectedModel) =>
      super.noSuchMethod(
        Invocation.setter(
          #loadSelectedModel,
          _loadSelectedModel,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void selectModel(_i4.OpenRouterModel? model) => super.noSuchMethod(
        Invocation.method(
          #selectModel,
          [model],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectGlobalModel() => super.noSuchMethod(
        Invocation.method(
          #selectGlobalModel,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
