// Mocks generated by Mockito 5.4.6 from annotations
// in readeck_app/test/ui/settings/widgets/translation_settings_screen_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i6;

import 'package:flutter_command/flutter_command.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:readeck_app/domain/models/openrouter_model/openrouter_model.dart'
    as _i4;
import 'package:readeck_app/ui/settings/view_models/translation_settings_viewmodel.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCommand_0<TParam, TResult> extends _i1.SmartFake
    implements _i2.Command<TParam, TResult> {
  _FakeCommand_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TranslationSettingsViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockTranslationSettingsViewModel extends _i1.Mock
    implements _i3.TranslationSettingsViewModel {
  @override
  _i2.Command<String, void> get saveTranslationProvider => (super.noSuchMethod(
        Invocation.getter(#saveTranslationProvider),
        returnValue: _FakeCommand_0<String, void>(
          this,
          Invocation.getter(#saveTranslationProvider),
        ),
        returnValueForMissingStub: _FakeCommand_0<String, void>(
          this,
          Invocation.getter(#saveTranslationProvider),
        ),
      ) as _i2.Command<String, void>);

  @override
  _i2.Command<String, void> get saveTranslationTargetLanguage =>
      (super.noSuchMethod(
        Invocation.getter(#saveTranslationTargetLanguage),
        returnValue: _FakeCommand_0<String, void>(
          this,
          Invocation.getter(#saveTranslationTargetLanguage),
        ),
        returnValueForMissingStub: _FakeCommand_0<String, void>(
          this,
          Invocation.getter(#saveTranslationTargetLanguage),
        ),
      ) as _i2.Command<String, void>);

  @override
  _i2.Command<bool, void> get saveTranslationCacheEnabled =>
      (super.noSuchMethod(
        Invocation.getter(#saveTranslationCacheEnabled),
        returnValue: _FakeCommand_0<bool, void>(
          this,
          Invocation.getter(#saveTranslationCacheEnabled),
        ),
        returnValueForMissingStub: _FakeCommand_0<bool, void>(
          this,
          Invocation.getter(#saveTranslationCacheEnabled),
        ),
      ) as _i2.Command<bool, void>);

  @override
  _i2.Command<void, void> get loadTranslationSettings => (super.noSuchMethod(
        Invocation.getter(#loadTranslationSettings),
        returnValue: _FakeCommand_0<void, void>(
          this,
          Invocation.getter(#loadTranslationSettings),
        ),
        returnValueForMissingStub: _FakeCommand_0<void, void>(
          this,
          Invocation.getter(#loadTranslationSettings),
        ),
      ) as _i2.Command<void, void>);

  @override
  _i2.Command<void, List<_i4.OpenRouterModel>> get loadModels =>
      (super.noSuchMethod(
        Invocation.getter(#loadModels),
        returnValue: _FakeCommand_0<void, List<_i4.OpenRouterModel>>(
          this,
          Invocation.getter(#loadModels),
        ),
        returnValueForMissingStub:
            _FakeCommand_0<void, List<_i4.OpenRouterModel>>(
          this,
          Invocation.getter(#loadModels),
        ),
      ) as _i2.Command<void, List<_i4.OpenRouterModel>>);

  @override
  _i2.Command<void, void> get clearTranslationCache => (super.noSuchMethod(
        Invocation.getter(#clearTranslationCache),
        returnValue: _FakeCommand_0<void, void>(
          this,
          Invocation.getter(#clearTranslationCache),
        ),
        returnValueForMissingStub: _FakeCommand_0<void, void>(
          this,
          Invocation.getter(#clearTranslationCache),
        ),
      ) as _i2.Command<void, void>);

  @override
  String get translationProvider => (super.noSuchMethod(
        Invocation.getter(#translationProvider),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#translationProvider),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#translationProvider),
        ),
      ) as String);

  @override
  String get translationTargetLanguage => (super.noSuchMethod(
        Invocation.getter(#translationTargetLanguage),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#translationTargetLanguage),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#translationTargetLanguage),
        ),
      ) as String);

  @override
  bool get translationCacheEnabled => (super.noSuchMethod(
        Invocation.getter(#translationCacheEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get translationModel => (super.noSuchMethod(
        Invocation.getter(#translationModel),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#translationModel),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#translationModel),
        ),
      ) as String);

  @override
  String get translationModelName => (super.noSuchMethod(
        Invocation.getter(#translationModelName),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#translationModelName),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#translationModelName),
        ),
      ) as String);

  @override
  List<_i4.OpenRouterModel> get availableModels => (super.noSuchMethod(
        Invocation.getter(#availableModels),
        returnValue: <_i4.OpenRouterModel>[],
        returnValueForMissingStub: <_i4.OpenRouterModel>[],
      ) as List<_i4.OpenRouterModel>);

  @override
  set saveTranslationProvider(
          _i2.Command<String, void>? _saveTranslationProvider) =>
      super.noSuchMethod(
        Invocation.setter(
          #saveTranslationProvider,
          _saveTranslationProvider,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set saveTranslationTargetLanguage(
          _i2.Command<String, void>? _saveTranslationTargetLanguage) =>
      super.noSuchMethod(
        Invocation.setter(
          #saveTranslationTargetLanguage,
          _saveTranslationTargetLanguage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set saveTranslationCacheEnabled(
          _i2.Command<bool, void>? _saveTranslationCacheEnabled) =>
      super.noSuchMethod(
        Invocation.setter(
          #saveTranslationCacheEnabled,
          _saveTranslationCacheEnabled,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set loadTranslationSettings(
          _i2.Command<void, void>? _loadTranslationSettings) =>
      super.noSuchMethod(
        Invocation.setter(
          #loadTranslationSettings,
          _loadTranslationSettings,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set loadModels(_i2.Command<void, List<_i4.OpenRouterModel>>? _loadModels) =>
      super.noSuchMethod(
        Invocation.setter(
          #loadModels,
          _loadModels,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set clearTranslationCache(_i2.Command<void, void>? _clearTranslationCache) =>
      super.noSuchMethod(
        Invocation.setter(
          #clearTranslationCache,
          _clearTranslationCache,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
