// Mocks generated by Mockito 5.4.6 from annotations
// in readeck_app/test/unit/data/repository/ai_tag_recommendation/ai_tag_recommendation_repository_simple_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:readeck_app/data/repository/settings/settings_repository.dart'
    as _i7;
import 'package:readeck_app/data/service/openrouter_api_client.dart' as _i2;
import 'package:readeck_app/domain/models/openrouter_model/openrouter_model.dart'
    as _i6;
import 'package:result_dart/result_dart.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [OpenRouterApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenRouterApiClient extends _i1.Mock
    implements _i2.OpenRouterApiClient {
  MockOpenRouterApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConfigured => (super.noSuchMethod(
        Invocation.getter(#isConfigured),
        returnValue: false,
      ) as bool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Stream<_i4.ResultDart<String, Exception>> streamChatCompletion({
    required String? model,
    required List<Map<String, String>>? messages,
    double? temperature,
    int? maxTokens,
    double? topP,
    double? frequencyPenalty,
    double? presencePenalty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamChatCompletion,
          [],
          {
            #model: model,
            #messages: messages,
            #temperature: temperature,
            #maxTokens: maxTokens,
            #topP: topP,
            #frequencyPenalty: frequencyPenalty,
            #presencePenalty: presencePenalty,
          },
        ),
        returnValue: _i3.Stream<_i4.ResultDart<String, Exception>>.empty(),
      ) as _i3.Stream<_i4.ResultDart<String, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<String, Exception>> chatCompletion({
    required String? model,
    required List<Map<String, String>>? messages,
    double? temperature,
    int? maxTokens,
    double? topP,
    double? frequencyPenalty,
    double? presencePenalty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #chatCompletion,
          [],
          {
            #model: model,
            #messages: messages,
            #temperature: temperature,
            #maxTokens: maxTokens,
            #topP: topP,
            #frequencyPenalty: frequencyPenalty,
            #presencePenalty: presencePenalty,
          },
        ),
        returnValue: _i3.Future<_i4.ResultDart<String, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<String, Exception>>(
          this,
          Invocation.method(
            #chatCompletion,
            [],
            {
              #model: model,
              #messages: messages,
              #temperature: temperature,
              #maxTokens: maxTokens,
              #topP: topP,
              #frequencyPenalty: frequencyPenalty,
              #presencePenalty: presencePenalty,
            },
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<String, Exception>>);

  @override
  _i3.Stream<_i4.ResultDart<String, Exception>> streamCompletion({
    required String? model,
    required String? prompt,
    double? temperature,
    int? maxTokens,
    double? topP,
    double? frequencyPenalty,
    double? presencePenalty,
    List<String>? stop,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamCompletion,
          [],
          {
            #model: model,
            #prompt: prompt,
            #temperature: temperature,
            #maxTokens: maxTokens,
            #topP: topP,
            #frequencyPenalty: frequencyPenalty,
            #presencePenalty: presencePenalty,
            #stop: stop,
          },
        ),
        returnValue: _i3.Stream<_i4.ResultDart<String, Exception>>.empty(),
      ) as _i3.Stream<_i4.ResultDart<String, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<String, Exception>> completion({
    required String? model,
    required String? prompt,
    double? temperature,
    int? maxTokens,
    double? topP,
    double? frequencyPenalty,
    double? presencePenalty,
    List<String>? stop,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completion,
          [],
          {
            #model: model,
            #prompt: prompt,
            #temperature: temperature,
            #maxTokens: maxTokens,
            #topP: topP,
            #frequencyPenalty: frequencyPenalty,
            #presencePenalty: presencePenalty,
            #stop: stop,
          },
        ),
        returnValue: _i3.Future<_i4.ResultDart<String, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<String, Exception>>(
          this,
          Invocation.method(
            #completion,
            [],
            {
              #model: model,
              #prompt: prompt,
              #temperature: temperature,
              #maxTokens: maxTokens,
              #topP: topP,
              #frequencyPenalty: frequencyPenalty,
              #presencePenalty: presencePenalty,
              #stop: stop,
            },
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<String, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<List<_i6.OpenRouterModel>, Exception>> getModels(
          {String? category}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getModels,
          [],
          {#category: category},
        ),
        returnValue: _i3
            .Future<_i4.ResultDart<List<_i6.OpenRouterModel>, Exception>>.value(
            _i5.dummyValue<
                _i4.ResultDart<List<_i6.OpenRouterModel>, Exception>>(
          this,
          Invocation.method(
            #getModels,
            [],
            {#category: category},
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<List<_i6.OpenRouterModel>, Exception>>);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i7.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<void> get settingsChanged => (super.noSuchMethod(
        Invocation.getter(#settingsChanged),
        returnValue: _i3.Stream<void>.empty(),
      ) as _i3.Stream<void>);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> loadSettings() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadSettings,
          [],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #loadSettings,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  bool isApiConfigured() => (super.noSuchMethod(
        Invocation.method(
          #isApiConfigured,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> saveApiConfig(
    String? host,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveApiConfig,
          [
            host,
            token,
          ],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveApiConfig,
            [
              host,
              token,
            ],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  (String, String) getApiConfig() => (super.noSuchMethod(
        Invocation.method(
          #getApiConfig,
          [],
        ),
        returnValue: (
          _i5.dummyValue<String>(
            this,
            Invocation.method(
              #getApiConfig,
              [],
            ),
          ),
          _i5.dummyValue<String>(
            this,
            Invocation.method(
              #getApiConfig,
              [],
            ),
          )
        ),
      ) as (String, String));

  @override
  int getThemeMode() => (super.noSuchMethod(
        Invocation.method(
          #getThemeMode,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> saveThemeMode(int? themeMode) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveThemeMode,
          [themeMode],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveThemeMode,
            [themeMode],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> saveOpenRouterApiKey(
          String? apiKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveOpenRouterApiKey,
          [apiKey],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveOpenRouterApiKey,
            [apiKey],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  String getOpenRouterApiKey() => (super.noSuchMethod(
        Invocation.method(
          #getOpenRouterApiKey,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getOpenRouterApiKey,
            [],
          ),
        ),
      ) as String);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> saveTranslationProvider(
          String? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTranslationProvider,
          [provider],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveTranslationProvider,
            [provider],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  String getTranslationProvider() => (super.noSuchMethod(
        Invocation.method(
          #getTranslationProvider,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getTranslationProvider,
            [],
          ),
        ),
      ) as String);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> saveTranslationTargetLanguage(
          String? language) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTranslationTargetLanguage,
          [language],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveTranslationTargetLanguage,
            [language],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  String getTranslationTargetLanguage() => (super.noSuchMethod(
        Invocation.method(
          #getTranslationTargetLanguage,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getTranslationTargetLanguage,
            [],
          ),
        ),
      ) as String);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> saveTranslationCacheEnabled(
          bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTranslationCacheEnabled,
          [enabled],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveTranslationCacheEnabled,
            [enabled],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  bool getTranslationCacheEnabled() => (super.noSuchMethod(
        Invocation.method(
          #getTranslationCacheEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> saveSelectedOpenRouterModel(
          String? modelId) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSelectedOpenRouterModel,
          [modelId],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveSelectedOpenRouterModel,
            [modelId],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  String getSelectedOpenRouterModel() => (super.noSuchMethod(
        Invocation.method(
          #getSelectedOpenRouterModel,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getSelectedOpenRouterModel,
            [],
          ),
        ),
      ) as String);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> saveAiTagTargetLanguage(
          String? language) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAiTagTargetLanguage,
          [language],
        ),
        returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
            _i5.dummyValue<_i4.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #saveAiTagTargetLanguage,
            [language],
          ),
        )),
      ) as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  String getAiTagTargetLanguage() => (super.noSuchMethod(
        Invocation.method(
          #getAiTagTargetLanguage,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getAiTagTargetLanguage,
            [],
          ),
        ),
      ) as String);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
